name: Jamz Entertainment
favicon: null
layout_spectrum: 0.22476
typography_spectrum: 0.3725054080132395
title: 'Jamz Entertainment '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefcfe'
    - '#565457'
    - '#7c7a7d'
    - '#c6c4c5'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
